[dependencies]
redis = "0.23.0"
serde = "1.0"
syn = "2"
quote = "1"
darling = "0.20"


[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/test.rs"

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }